# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Hannah Pinson
description: >- # this means to ignore newlines until "baseurl:"
  Website of Hannah Pinson.
baseurl: "" # the subpath of the site
url: "https://hannahpinson.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
#google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: About
    #- name: Research

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: Hannah dot pinson at vub dot be
      #link: mailto:yourmail@domain.com
  follow:
    - name: Twitter
      link: http://twitter.com/Hannah76617590
    - name: LinkedIn
      link: http://linkedin.com/in/hannah-pinson-95b805b6


# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
